// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package com.hopehack.interlaken.common.protobuf;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.protobuf.Msg.Type type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.protobuf.Msg.Type type = 2;</code>
   * @return The type.
   */
  Msg.Type getType();

  /**
   * <code>.protobuf.Msg.Ping ping = 3;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.protobuf.Msg.Ping ping = 3;</code>
   * @return The ping.
   */
  Msg.Ping getPing();
  /**
   * <code>.protobuf.Msg.Ping ping = 3;</code>
   */
  Msg.PingOrBuilder getPingOrBuilder();

  /**
   * <code>.protobuf.Msg.Pong pong = 4;</code>
   * @return Whether the pong field is set.
   */
  boolean hasPong();
  /**
   * <code>.protobuf.Msg.Pong pong = 4;</code>
   * @return The pong.
   */
  Msg.Pong getPong();
  /**
   * <code>.protobuf.Msg.Pong pong = 4;</code>
   */
  Msg.PongOrBuilder getPongOrBuilder();

  /**
   * <code>.protobuf.Msg.Login login = 5;</code>
   * @return Whether the login field is set.
   */
  boolean hasLogin();
  /**
   * <code>.protobuf.Msg.Login login = 5;</code>
   * @return The login.
   */
  Msg.Login getLogin();
  /**
   * <code>.protobuf.Msg.Login login = 5;</code>
   */
  Msg.LoginOrBuilder getLoginOrBuilder();

  /**
   * <code>.protobuf.Msg.LoginOut loginOut = 6;</code>
   * @return Whether the loginOut field is set.
   */
  boolean hasLoginOut();
  /**
   * <code>.protobuf.Msg.LoginOut loginOut = 6;</code>
   * @return The loginOut.
   */
  Msg.LoginOut getLoginOut();
  /**
   * <code>.protobuf.Msg.LoginOut loginOut = 6;</code>
   */
  Msg.LoginOutOrBuilder getLoginOutOrBuilder();

  /**
   * <code>.protobuf.Msg.Message message = 7;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.protobuf.Msg.Message message = 7;</code>
   * @return The message.
   */
  Msg.Message getMessage();
  /**
   * <code>.protobuf.Msg.Message message = 7;</code>
   */
  Msg.MessageOrBuilder getMessageOrBuilder();

  public Msg.BodyCase getBodyCase();
}
