// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package com.hopehack.interlaken.common.protobuf;

public final class MsgWrapper {
  private MsgWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Msg_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Msg_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Msg_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Msg_Pong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Msg_Login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Msg_Login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Msg_LoginOut_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Msg_LoginOut_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Msg_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Msg_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016MsgProto.proto\022\010protobuf\"\250\004\n\003Msg\022\n\n\002id" +
      "\030\001 \001(\003\022 \n\004type\030\002 \001(\0162\022.protobuf.Msg.Type" +
      "\022\"\n\004ping\030\003 \001(\0132\022.protobuf.Msg.PingH\000\022\"\n\004" +
      "pong\030\004 \001(\0132\022.protobuf.Msg.PongH\000\022$\n\005logi" +
      "n\030\005 \001(\0132\023.protobuf.Msg.LoginH\000\022*\n\010loginO" +
      "ut\030\006 \001(\0132\026.protobuf.Msg.LoginOutH\000\022(\n\007me" +
      "ssage\030\007 \001(\0132\025.protobuf.Msg.MessageH\000\032\027\n\004" +
      "Ping\022\017\n\007content\030\001 \001(\t\032\027\n\004Pong\022\017\n\007content" +
      "\030\001 \001(\t\032P\n\005Login\022\020\n\010deviceId\030\001 \001(\t\022\022\n\napp" +
      "Version\030\002 \001(\t\022\016\n\006userId\030\003 \001(\t\022\021\n\tosVersi" +
      "on\030\004 \001(\t\032\032\n\010LoginOut\022\016\n\006userId\030\001 \001(\t\032E\n\007" +
      "Message\022\014\n\004type\030\001 \001(\005\022\016\n\006target\030\002 \001(\t\022\017\n" +
      "\007content\030\003 \001(\t\022\013\n\003ext\030\004 \001(\t\"@\n\004Type\022\010\n\004P" +
      "ING\020\000\022\010\n\004PONG\020\001\022\t\n\005LOGIN\020\002\022\014\n\010LOGINOUT\020\003" +
      "\022\013\n\007MESSAGE\020\004B\006\n\004bodyB7\n\'com.hopehack.in" +
      "terlaken.common.protobufB\nMsgWrapperP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Msg_descriptor,
        new String[] { "Id", "Type", "Ping", "Pong", "Login", "LoginOut", "Message", "Body", });
    internal_static_protobuf_Msg_Ping_descriptor =
      internal_static_protobuf_Msg_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Msg_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Msg_Ping_descriptor,
        new String[] { "Content", });
    internal_static_protobuf_Msg_Pong_descriptor =
      internal_static_protobuf_Msg_descriptor.getNestedTypes().get(1);
    internal_static_protobuf_Msg_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Msg_Pong_descriptor,
        new String[] { "Content", });
    internal_static_protobuf_Msg_Login_descriptor =
      internal_static_protobuf_Msg_descriptor.getNestedTypes().get(2);
    internal_static_protobuf_Msg_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Msg_Login_descriptor,
        new String[] { "DeviceId", "AppVersion", "UserId", "OsVersion", });
    internal_static_protobuf_Msg_LoginOut_descriptor =
      internal_static_protobuf_Msg_descriptor.getNestedTypes().get(3);
    internal_static_protobuf_Msg_LoginOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Msg_LoginOut_descriptor,
        new String[] { "UserId", });
    internal_static_protobuf_Msg_Message_descriptor =
      internal_static_protobuf_Msg_descriptor.getNestedTypes().get(4);
    internal_static_protobuf_Msg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Msg_Message_descriptor,
        new String[] { "Type", "Target", "Content", "Ext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
